/* tslint:disable */
/* eslint-disable */
/**
 * Cadence API
 * Cadence ERP powers your business with a single platform for all your HR, Class Management, Staff Scheduling, Time Tracking & Communication needs.
 *
 * The version of the OpenAPI document: 1.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Employee,
  EmployeeQualification,
  EmploymentType,
  PatchedEmployee,
  PatchedEmployeeQualification,
  PatchedEmploymentType,
  PatchedQualification,
  PatchedWorkLocation,
  Qualification,
  WorkLocation,
} from '../models/index';
import {
    EmployeeFromJSON,
    EmployeeToJSON,
    EmployeeQualificationFromJSON,
    EmployeeQualificationToJSON,
    EmploymentTypeFromJSON,
    EmploymentTypeToJSON,
    PatchedEmployeeFromJSON,
    PatchedEmployeeToJSON,
    PatchedEmployeeQualificationFromJSON,
    PatchedEmployeeQualificationToJSON,
    PatchedEmploymentTypeFromJSON,
    PatchedEmploymentTypeToJSON,
    PatchedQualificationFromJSON,
    PatchedQualificationToJSON,
    PatchedWorkLocationFromJSON,
    PatchedWorkLocationToJSON,
    QualificationFromJSON,
    QualificationToJSON,
    WorkLocationFromJSON,
    WorkLocationToJSON,
} from '../models/index';

export interface HrEmployeeQualificationsCreateRequest {
    employeeQualification: Omit<EmployeeQualification, 'id'>;
}

export interface HrEmployeeQualificationsDestroyRequest {
    id: number;
}

export interface HrEmployeeQualificationsPartialUpdateRequest {
    id: number;
    patchedEmployeeQualification?: Omit<PatchedEmployeeQualification, 'id'>;
}

export interface HrEmployeeQualificationsRetrieveRequest {
    id: number;
}

export interface HrEmployeeQualificationsUpdateRequest {
    id: number;
    employeeQualification: Omit<EmployeeQualification, 'id'>;
}

export interface HrEmployeesCreateRequest {
    employee: Omit<Employee, 'id'>;
}

export interface HrEmployeesDestroyRequest {
    id: number;
}

export interface HrEmployeesPartialUpdateRequest {
    id: number;
    patchedEmployee?: Omit<PatchedEmployee, 'id'>;
}

export interface HrEmployeesRetrieveRequest {
    id: number;
}

export interface HrEmployeesUpdateRequest {
    id: number;
    employee: Omit<Employee, 'id'>;
}

export interface HrEmploymentTypesCreateRequest {
    employmentType: Omit<EmploymentType, 'id'>;
}

export interface HrEmploymentTypesDestroyRequest {
    id: number;
}

export interface HrEmploymentTypesPartialUpdateRequest {
    id: number;
    patchedEmploymentType?: Omit<PatchedEmploymentType, 'id'>;
}

export interface HrEmploymentTypesRetrieveRequest {
    id: number;
}

export interface HrEmploymentTypesUpdateRequest {
    id: number;
    employmentType: Omit<EmploymentType, 'id'>;
}

export interface HrQualificationsCreateRequest {
    qualification: Omit<Qualification, 'id'>;
}

export interface HrQualificationsDestroyRequest {
    id: number;
}

export interface HrQualificationsPartialUpdateRequest {
    id: number;
    patchedQualification?: Omit<PatchedQualification, 'id'>;
}

export interface HrQualificationsRetrieveRequest {
    id: number;
}

export interface HrQualificationsUpdateRequest {
    id: number;
    qualification: Omit<Qualification, 'id'>;
}

export interface HrWorkLocationsCreateRequest {
    workLocation: Omit<WorkLocation, 'id'>;
}

export interface HrWorkLocationsDestroyRequest {
    id: number;
}

export interface HrWorkLocationsPartialUpdateRequest {
    id: number;
    patchedWorkLocation?: Omit<PatchedWorkLocation, 'id'>;
}

export interface HrWorkLocationsRetrieveRequest {
    id: number;
}

export interface HrWorkLocationsUpdateRequest {
    id: number;
    workLocation: Omit<WorkLocation, 'id'>;
}

/**
 * 
 */
export class HrApi extends runtime.BaseAPI {

    /**
     */
    async hrEmployeeQualificationsCreateRaw(requestParameters: HrEmployeeQualificationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeQualification>> {
        if (requestParameters['employeeQualification'] == null) {
            throw new runtime.RequiredError(
                'employeeQualification',
                'Required parameter "employeeQualification" was null or undefined when calling hrEmployeeQualificationsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeQualificationToJSON(requestParameters['employeeQualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeQualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeeQualificationsCreate(requestParameters: HrEmployeeQualificationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeQualification> {
        const response = await this.hrEmployeeQualificationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeeQualificationsDestroyRaw(requestParameters: HrEmployeeQualificationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeeQualificationsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async hrEmployeeQualificationsDestroy(requestParameters: HrEmployeeQualificationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.hrEmployeeQualificationsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async hrEmployeeQualificationsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmployeeQualification>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmployeeQualificationFromJSON));
    }

    /**
     */
    async hrEmployeeQualificationsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmployeeQualification>> {
        const response = await this.hrEmployeeQualificationsListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeeQualificationsPartialUpdateRaw(requestParameters: HrEmployeeQualificationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeQualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeeQualificationsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedEmployeeQualificationToJSON(requestParameters['patchedEmployeeQualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeQualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeeQualificationsPartialUpdate(requestParameters: HrEmployeeQualificationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeQualification> {
        const response = await this.hrEmployeeQualificationsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeeQualificationsRetrieveRaw(requestParameters: HrEmployeeQualificationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeQualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeeQualificationsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeQualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeeQualificationsRetrieve(requestParameters: HrEmployeeQualificationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeQualification> {
        const response = await this.hrEmployeeQualificationsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeeQualificationsUpdateRaw(requestParameters: HrEmployeeQualificationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeeQualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeeQualificationsUpdate().'
            );
        }

        if (requestParameters['employeeQualification'] == null) {
            throw new runtime.RequiredError(
                'employeeQualification',
                'Required parameter "employeeQualification" was null or undefined when calling hrEmployeeQualificationsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employee-qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeQualificationToJSON(requestParameters['employeeQualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeQualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeeQualificationsUpdate(requestParameters: HrEmployeeQualificationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeeQualification> {
        const response = await this.hrEmployeeQualificationsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeesCreateRaw(requestParameters: HrEmployeesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Employee>> {
        if (requestParameters['employee'] == null) {
            throw new runtime.RequiredError(
                'employee',
                'Required parameter "employee" was null or undefined when calling hrEmployeesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeToJSON(requestParameters['employee']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeesCreate(requestParameters: HrEmployeesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Employee> {
        const response = await this.hrEmployeesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeesDestroyRaw(requestParameters: HrEmployeesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async hrEmployeesDestroy(requestParameters: HrEmployeesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.hrEmployeesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async hrEmployeesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Employee>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmployeeFromJSON));
    }

    /**
     */
    async hrEmployeesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Employee>> {
        const response = await this.hrEmployeesListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeesPartialUpdateRaw(requestParameters: HrEmployeesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Employee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedEmployeeToJSON(requestParameters['patchedEmployee']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeesPartialUpdate(requestParameters: HrEmployeesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Employee> {
        const response = await this.hrEmployeesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeesRetrieveRaw(requestParameters: HrEmployeesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Employee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeesRetrieve(requestParameters: HrEmployeesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Employee> {
        const response = await this.hrEmployeesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmployeesUpdateRaw(requestParameters: HrEmployeesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Employee>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmployeesUpdate().'
            );
        }

        if (requestParameters['employee'] == null) {
            throw new runtime.RequiredError(
                'employee',
                'Required parameter "employee" was null or undefined when calling hrEmployeesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employees/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmployeeToJSON(requestParameters['employee']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmployeesUpdate(requestParameters: HrEmployeesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Employee> {
        const response = await this.hrEmployeesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmploymentTypesCreateRaw(requestParameters: HrEmploymentTypesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmploymentType>> {
        if (requestParameters['employmentType'] == null) {
            throw new runtime.RequiredError(
                'employmentType',
                'Required parameter "employmentType" was null or undefined when calling hrEmploymentTypesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmploymentTypeToJSON(requestParameters['employmentType']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmploymentTypeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmploymentTypesCreate(requestParameters: HrEmploymentTypesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmploymentType> {
        const response = await this.hrEmploymentTypesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmploymentTypesDestroyRaw(requestParameters: HrEmploymentTypesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmploymentTypesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async hrEmploymentTypesDestroy(requestParameters: HrEmploymentTypesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.hrEmploymentTypesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async hrEmploymentTypesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmploymentType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmploymentTypeFromJSON));
    }

    /**
     */
    async hrEmploymentTypesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmploymentType>> {
        const response = await this.hrEmploymentTypesListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmploymentTypesPartialUpdateRaw(requestParameters: HrEmploymentTypesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmploymentType>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmploymentTypesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedEmploymentTypeToJSON(requestParameters['patchedEmploymentType']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmploymentTypeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmploymentTypesPartialUpdate(requestParameters: HrEmploymentTypesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmploymentType> {
        const response = await this.hrEmploymentTypesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmploymentTypesRetrieveRaw(requestParameters: HrEmploymentTypesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmploymentType>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmploymentTypesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmploymentTypeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmploymentTypesRetrieve(requestParameters: HrEmploymentTypesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmploymentType> {
        const response = await this.hrEmploymentTypesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrEmploymentTypesUpdateRaw(requestParameters: HrEmploymentTypesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmploymentType>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrEmploymentTypesUpdate().'
            );
        }

        if (requestParameters['employmentType'] == null) {
            throw new runtime.RequiredError(
                'employmentType',
                'Required parameter "employmentType" was null or undefined when calling hrEmploymentTypesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/employment-types/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EmploymentTypeToJSON(requestParameters['employmentType']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmploymentTypeFromJSON(jsonValue));
    }

    /**
     */
    async hrEmploymentTypesUpdate(requestParameters: HrEmploymentTypesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmploymentType> {
        const response = await this.hrEmploymentTypesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrQualificationsCreateRaw(requestParameters: HrQualificationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Qualification>> {
        if (requestParameters['qualification'] == null) {
            throw new runtime.RequiredError(
                'qualification',
                'Required parameter "qualification" was null or undefined when calling hrQualificationsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QualificationToJSON(requestParameters['qualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrQualificationsCreate(requestParameters: HrQualificationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Qualification> {
        const response = await this.hrQualificationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrQualificationsDestroyRaw(requestParameters: HrQualificationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrQualificationsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async hrQualificationsDestroy(requestParameters: HrQualificationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.hrQualificationsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async hrQualificationsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Qualification>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QualificationFromJSON));
    }

    /**
     */
    async hrQualificationsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Qualification>> {
        const response = await this.hrQualificationsListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async hrQualificationsPartialUpdateRaw(requestParameters: HrQualificationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Qualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrQualificationsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedQualificationToJSON(requestParameters['patchedQualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrQualificationsPartialUpdate(requestParameters: HrQualificationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Qualification> {
        const response = await this.hrQualificationsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrQualificationsRetrieveRaw(requestParameters: HrQualificationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Qualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrQualificationsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrQualificationsRetrieve(requestParameters: HrQualificationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Qualification> {
        const response = await this.hrQualificationsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrQualificationsUpdateRaw(requestParameters: HrQualificationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Qualification>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrQualificationsUpdate().'
            );
        }

        if (requestParameters['qualification'] == null) {
            throw new runtime.RequiredError(
                'qualification',
                'Required parameter "qualification" was null or undefined when calling hrQualificationsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/qualifications/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QualificationToJSON(requestParameters['qualification']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QualificationFromJSON(jsonValue));
    }

    /**
     */
    async hrQualificationsUpdate(requestParameters: HrQualificationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Qualification> {
        const response = await this.hrQualificationsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrWorkLocationsCreateRaw(requestParameters: HrWorkLocationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkLocation>> {
        if (requestParameters['workLocation'] == null) {
            throw new runtime.RequiredError(
                'workLocation',
                'Required parameter "workLocation" was null or undefined when calling hrWorkLocationsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkLocationToJSON(requestParameters['workLocation']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkLocationFromJSON(jsonValue));
    }

    /**
     */
    async hrWorkLocationsCreate(requestParameters: HrWorkLocationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkLocation> {
        const response = await this.hrWorkLocationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrWorkLocationsDestroyRaw(requestParameters: HrWorkLocationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrWorkLocationsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async hrWorkLocationsDestroy(requestParameters: HrWorkLocationsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.hrWorkLocationsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async hrWorkLocationsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkLocation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkLocationFromJSON));
    }

    /**
     */
    async hrWorkLocationsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkLocation>> {
        const response = await this.hrWorkLocationsListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async hrWorkLocationsPartialUpdateRaw(requestParameters: HrWorkLocationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkLocation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrWorkLocationsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedWorkLocationToJSON(requestParameters['patchedWorkLocation']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkLocationFromJSON(jsonValue));
    }

    /**
     */
    async hrWorkLocationsPartialUpdate(requestParameters: HrWorkLocationsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkLocation> {
        const response = await this.hrWorkLocationsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrWorkLocationsRetrieveRaw(requestParameters: HrWorkLocationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkLocation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrWorkLocationsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkLocationFromJSON(jsonValue));
    }

    /**
     */
    async hrWorkLocationsRetrieve(requestParameters: HrWorkLocationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkLocation> {
        const response = await this.hrWorkLocationsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hrWorkLocationsUpdateRaw(requestParameters: HrWorkLocationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkLocation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hrWorkLocationsUpdate().'
            );
        }

        if (requestParameters['workLocation'] == null) {
            throw new runtime.RequiredError(
                'workLocation',
                'Required parameter "workLocation" was null or undefined when calling hrWorkLocationsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/hr/work-locations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkLocationToJSON(requestParameters['workLocation']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkLocationFromJSON(jsonValue));
    }

    /**
     */
    async hrWorkLocationsUpdate(requestParameters: HrWorkLocationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkLocation> {
        const response = await this.hrWorkLocationsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
