/* tslint:disable */
/* eslint-disable */
/**
 * Cadence API
 * Cadence ERP powers your business with a single platform for all your HR, Class Management, Staff Scheduling, Time Tracking & Communication needs.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmployeeQualification } from './EmployeeQualification';
import {
    EmployeeQualificationFromJSON,
    EmployeeQualificationFromJSONTyped,
    EmployeeQualificationToJSON,
    EmployeeQualificationToJSONTyped,
} from './EmployeeQualification';

/**
 * 
 * @export
 * @interface PaginatedEmployeeQualificationList
 */
export interface PaginatedEmployeeQualificationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEmployeeQualificationList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEmployeeQualificationList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEmployeeQualificationList
     */
    previous?: string;
    /**
     * 
     * @type {Array<EmployeeQualification>}
     * @memberof PaginatedEmployeeQualificationList
     */
    results: Array<EmployeeQualification>;
}

/**
 * Check if a given object implements the PaginatedEmployeeQualificationList interface.
 */
export function instanceOfPaginatedEmployeeQualificationList(value: object): value is PaginatedEmployeeQualificationList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedEmployeeQualificationListFromJSON(json: any): PaginatedEmployeeQualificationList {
    return PaginatedEmployeeQualificationListFromJSONTyped(json, false);
}

export function PaginatedEmployeeQualificationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEmployeeQualificationList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(EmployeeQualificationFromJSON)),
    };
}

export function PaginatedEmployeeQualificationListToJSON(json: any): PaginatedEmployeeQualificationList {
    return PaginatedEmployeeQualificationListToJSONTyped(json, false);
}

export function PaginatedEmployeeQualificationListToJSONTyped(value?: PaginatedEmployeeQualificationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(EmployeeQualificationToJSON)),
    };
}

