/* tslint:disable */
/* eslint-disable */
/**
 * Cadence API
 * Cadence ERP powers your business with a single platform for all your HR, Class Management, Staff Scheduling, Time Tracking & Communication needs.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionStatus
 */
export interface SessionStatus {
    /**
     * 
     * @type {string}
     * @memberof SessionStatus
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof SessionStatus
     */
    user?: string;
}

/**
 * Check if a given object implements the SessionStatus interface.
 */
export function instanceOfSessionStatus(value: object): value is SessionStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SessionStatusFromJSON(json: any): SessionStatus {
    return SessionStatusFromJSONTyped(json, false);
}

export function SessionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function SessionStatusToJSON(json: any): SessionStatus {
    return SessionStatusToJSONTyped(json, false);
}

export function SessionStatusToJSONTyped(value?: SessionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'user': value['user'],
    };
}

